"""Code generation service for inference scripts and deployment."""

from typing import Dict, Any
from models.schemas import GeneratedCode
from utils.logger import get_logger
from jinja2 import Template

logger = get_logger(__name__)


class CodeGenerator:
    """Service for generating deployment code and documentation."""
    
    def __init__(self):
        """Initialize code generator."""
        pass
    
    def generate_inference_script(
        self,
        model_info: Dict[str, Any],
        config: Dict[str, Any]
    ) -> GeneratedCode:
        """Generate Python inference script.
        
        Args:
            model_info: Model information
            config: Training configuration
            
        Returns:
            GeneratedCode object
        """
        logger.info(f"Generating inference script for {model_info.get('model_id')}")
        
        template = Template('''"""
Inference script for QLoRA fine-tuned {{ model_id }}
Generated by LLM Fine-Tuning Pipeline
Uses 4-bit quantization for efficient inference
"""

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
{% if use_lora %}from peft import PeftModel, PeftConfig{% endif %}


def load_model(model_path: str, device: str = "cuda"):
    """Load the QLoRA fine-tuned model and tokenizer.
    
    Args:
        model_path: Path to the fine-tuned model (LoRA adapters)
        device: Device to load model on ('cuda' or 'cpu')
        
    Returns:
        Tuple of (model, tokenizer)
    """
    print(f"Loading tokenizer from {model_path}...")
    tokenizer = AutoTokenizer.from_pretrained(model_path)
    
    print(f"Loading base model with QLoRA 4-bit quantization...")
    {% if quantization == "4bit" %}
    # QLoRA: Load base model with 4-bit NF4 quantization
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_compute_dtype=torch.float16,
        bnb_4bit_quant_type="nf4",  # NormalFloat 4-bit
        bnb_4bit_use_double_quant=True  # Nested quantization
    )
    
    {% if use_lora %}
    # Load PeftConfig to get base model name
    peft_config = PeftConfig.from_pretrained(model_path)
    
    # Load quantized base model
    model = AutoModelForCausalLM.from_pretrained(
        peft_config.base_model_name_or_path,
        quantization_config=bnb_config,
        device_map="auto",
        torch_dtype=torch.float16,
        trust_remote_code=True
    )
    
    # Load LoRA adapters
    print(f"Loading LoRA adapters from {model_path}...")
    model = PeftModel.from_pretrained(model, model_path)
    {% else %}
    model = AutoModelForCausalLM.from_pretrained(
        model_path,
        quantization_config=bnb_config,
        device_map="auto",
        torch_dtype=torch.float16,
        trust_remote_code=True
    )
    {% endif %}
    {% elif quantization == "8bit" %}
    # Load with 8-bit quantization
    model = AutoModelForCausalLM.from_pretrained(
        model_path,
        load_in_8bit=True,
        device_map="auto",
        trust_remote_code=True
    )
    {% else %}
    # Load in FP16
    model = AutoModelForCausalLM.from_pretrained(
        model_path,
        torch_dtype=torch.float16,
        device_map="auto",
        trust_remote_code=True
    )
    {% endif %}
    
    model.eval()
    print("QLoRA model loaded successfully!")
    print(f"Model memory footprint: ~{torch.cuda.max_memory_allocated() / 1024**3:.2f} GB")
    
    return model, tokenizer


def generate_text(
    model,
    tokenizer,
    prompt: str,
    max_new_tokens: int = {{ max_seq_length }},
    temperature: float = 0.7,
    top_p: float = 0.9,
    top_k: int = 50,
    repetition_penalty: float = 1.1
) -> str:
    """Generate text from a prompt.
    
    Args:
        model: Loaded model
        tokenizer: Loaded tokenizer
        prompt: Input prompt
        max_new_tokens: Maximum tokens to generate
        temperature: Sampling temperature (higher = more random)
        top_p: Nucleus sampling parameter
        top_k: Top-k sampling parameter
        repetition_penalty: Repetition penalty
        
    Returns:
        Generated text
    """
    # Tokenize input
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    
    # Generate
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=temperature,
            top_p=top_p,
            top_k=top_k,
            repetition_penalty=repetition_penalty,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )
    
    # Decode
    generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
    
    return generated_text


def main():
    """Example usage."""
    # Configuration
    MODEL_PATH = "./output/final_model"  # Update with your model path
    
    # Load model
    model, tokenizer = load_model(MODEL_PATH)
    
    # Example prompts
    prompts = [
        "{{ example_prompt_1 }}",
        "{{ example_prompt_2 }}"
    ]
    
    # Generate
    for prompt in prompts:
        print(f"\\n{'='*60}")
        print(f"Prompt: {prompt}")
        print(f"{'='*60}")
        
        generated = generate_text(model, tokenizer, prompt)
        print(f"Generated:\\n{generated}")


if __name__ == "__main__":
    main()
''')
        
        code = template.render(
            model_id=model_info.get('model_id', 'unknown'),
            use_lora=config.get('use_lora', True),
            quantization=config.get('quantization'),
            max_seq_length=config.get('max_seq_length', 512),
            example_prompt_1=self._get_example_prompt(config.get('task_type', 'text-generation'), 1),
            example_prompt_2=self._get_example_prompt(config.get('task_type', 'text-generation'), 2)
        )
        
        return GeneratedCode(
            code=code,
            filename="inference.py",
            language="python",
            description="Standalone inference script for the fine-tuned model"
        )
    
    def generate_gradio_app(
        self,
        model_info: Dict[str, Any],
        config: Dict[str, Any]
    ) -> GeneratedCode:
        """Generate Gradio demo application.
        
        Args:
            model_info: Model information
            config: Training configuration
            
        Returns:
            GeneratedCode object
        """
        logger.info(f"Generating Gradio app for {model_info.get('model_id')}")
        
        template = Template('''"""
Gradio Demo for fine-tuned {{ model_id }}
Generated by LLM Fine-Tuning Pipeline
"""

import torch
import gradio as gr
from transformers import AutoModelForCausalLM, AutoTokenizer
{% if use_lora %}from peft import PeftModel{% endif %}


# Global variables
model = None
tokenizer = None


def load_model(model_path: str):
    """Load the model and tokenizer."""
    global model, tokenizer
    
    print("Loading model...")
    tokenizer = AutoTokenizer.from_pretrained(model_path)
    
    {% if quantization == "4bit" %}
    from transformers import BitsAndBytesConfig
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_compute_dtype=torch.float16
    )
    model = AutoModelForCausalLM.from_pretrained(
        model_path,
        quantization_config=bnb_config,
        device_map="auto"
    )
    {% else %}
    model = AutoModelForCausalLM.from_pretrained(
        model_path,
        torch_dtype=torch.float16,
        device_map="auto"
    )
    {% endif %}
    
    {% if use_lora %}
    model = PeftModel.from_pretrained(model, model_path)
    {% endif %}
    
    model.eval()
    print("Model loaded!")


def generate(
    prompt: str,
    max_tokens: int = 256,
    temperature: float = 0.7,
    top_p: float = 0.9,
    top_k: int = 50
) -> str:
    """Generate text from prompt."""
    if model is None or tokenizer is None:
        return "Error: Model not loaded. Please load a model first."
    
    try:
        inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
        
        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=max_tokens,
                temperature=temperature,
                top_p=top_p,
                top_k=top_k,
                do_sample=True,
                pad_token_id=tokenizer.eos_token_id
            )
        
        generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
        return generated_text
        
    except Exception as e:
        return f"Error during generation: {str(e)}"


# Create Gradio interface
def create_interface():
    """Create Gradio UI."""
    
    with gr.Blocks(title="{{ model_id }} - Fine-tuned Model Demo") as demo:
        gr.Markdown("# 🤖 {{ model_id }} - Fine-tuned Model")
        gr.Markdown("Interactive demo for your fine-tuned language model")
        
        with gr.Row():
            with gr.Column():
                prompt_input = gr.Textbox(
                    label="Prompt",
                    placeholder="Enter your prompt here...",
                    lines=5
                )
                
                with gr.Row():
                    max_tokens = gr.Slider(
                        minimum=50,
                        maximum=1024,
                        value=256,
                        step=50,
                        label="Max Tokens"
                    )
                    temperature = gr.Slider(
                        minimum=0.1,
                        maximum=2.0,
                        value=0.7,
                        step=0.1,
                        label="Temperature"
                    )
                
                with gr.Row():
                    top_p = gr.Slider(
                        minimum=0.1,
                        maximum=1.0,
                        value=0.9,
                        step=0.05,
                        label="Top P"
                    )
                    top_k = gr.Slider(
                        minimum=1,
                        maximum=100,
                        value=50,
                        step=1,
                        label="Top K"
                    )
                
                generate_btn = gr.Button("Generate", variant="primary")
            
            with gr.Column():
                output = gr.Textbox(
                    label="Generated Text",
                    lines=15
                )
        
        # Examples
        gr.Examples(
            examples=[
                ["{{ example_prompt_1 }}"],
                ["{{ example_prompt_2 }}"],
                ["{{ example_prompt_3 }}"]
            ],
            inputs=[prompt_input]
        )
        
        # Connect button
        generate_btn.click(
            fn=generate,
            inputs=[prompt_input, max_tokens, temperature, top_p, top_k],
            outputs=output
        )
    
    return demo


def main():
    """Main function."""
    import argparse
    
    parser = argparse.ArgumentParser(description="Gradio demo for fine-tuned model")
    parser.add_argument("--model-path", type=str, required=True, help="Path to model")
    parser.add_argument("--share", action="store_true", help="Create public link")
    parser.add_argument("--port", type=int, default=7860, help="Port number")
    
    args = parser.parse_args()
    
    # Load model
    load_model(args.model_path)
    
    # Create and launch interface
    demo = create_interface()
    demo.launch(server_name="0.0.0.0", server_port=args.port, share=args.share)


if __name__ == "__main__":
    main()
''')
        
        code = template.render(
            model_id=model_info.get('model_id', 'unknown'),
            use_lora=config.get('use_lora', True),
            quantization=config.get('quantization'),
            example_prompt_1=self._get_example_prompt(config.get('task_type', 'text-generation'), 1),
            example_prompt_2=self._get_example_prompt(config.get('task_type', 'text-generation'), 2),
            example_prompt_3=self._get_example_prompt(config.get('task_type', 'text-generation'), 3)
        )
        
        return GeneratedCode(
            code=code,
            filename="gradio_app.py",
            language="python",
            description="Interactive Gradio web application for model inference"
        )
    
    def generate_api_wrapper(
        self,
        model_info: Dict[str, Any],
        config: Dict[str, Any]
    ) -> GeneratedCode:
        """Generate FastAPI inference endpoint.
        
        Args:
            model_info: Model information
            config: Training configuration
            
        Returns:
            GeneratedCode object
        """
        logger.info(f"Generating API wrapper for {model_info.get('model_id')}")
        
        template = Template('''"""
FastAPI inference endpoint for {{ model_id }}
Generated by LLM Fine-Tuning Pipeline
"""

import torch
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
from transformers import AutoModelForCausalLM, AutoTokenizer
{% if use_lora %}from peft import PeftModel{% endif %}
from typing import Optional
import uvicorn


# Request/Response models
class GenerateRequest(BaseModel):
    """Request model for text generation."""
    prompt: str = Field(..., description="Input prompt")
    max_tokens: int = Field(256, ge=1, le=2048, description="Maximum tokens to generate")
    temperature: float = Field(0.7, ge=0.1, le=2.0, description="Sampling temperature")
    top_p: float = Field(0.9, ge=0.0, le=1.0, description="Nucleus sampling")
    top_k: int = Field(50, ge=1, le=100, description="Top-k sampling")
    repetition_penalty: float = Field(1.1, ge=1.0, le=2.0)


class GenerateResponse(BaseModel):
    """Response model for text generation."""
    generated_text: str
    prompt: str
    tokens_generated: int


# Global model state
app = FastAPI(
    title="{{ model_id }} Inference API",
    description="API for fine-tuned model inference",
    version="1.0.0"
)

model = None
tokenizer = None


@app.on_event("startup")
async def load_model():
    """Load model on startup."""
    global model, tokenizer
    
    MODEL_PATH = "./output/final_model"  # Configure this
    
    print("Loading model...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
    
    {% if quantization == "4bit" %}
    from transformers import BitsAndBytesConfig
    bnb_config = BitsAndBytesConfig(load_in_4bit=True)
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_PATH,
        quantization_config=bnb_config,
        device_map="auto"
    )
    {% else %}
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_PATH,
        torch_dtype=torch.float16,
        device_map="auto"
    )
    {% endif %}
    
    {% if use_lora %}
    model = PeftModel.from_pretrained(model, MODEL_PATH)
    {% endif %}
    
    model.eval()
    print("Model loaded successfully!")


@app.get("/")
async def root():
    """Root endpoint."""
    return {
        "message": "{{ model_id }} Inference API",
        "version": "1.0.0",
        "endpoints": ["/generate", "/health"]
    }


@app.get("/health")
async def health_check():
    """Health check endpoint."""
    return {
        "status": "healthy",
        "model_loaded": model is not None
    }


@app.post("/generate", response_model=GenerateResponse)
async def generate_text(request: GenerateRequest):
    """Generate text from prompt.
    
    Args:
        request: Generation request
        
    Returns:
        Generated text response
    """
    if model is None or tokenizer is None:
        raise HTTPException(status_code=503, detail="Model not loaded")
    
    try:
        # Tokenize
        inputs = tokenizer(request.prompt, return_tensors="pt").to(model.device)
        input_length = inputs.input_ids.shape[1]
        
        # Generate
        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=request.max_tokens,
                temperature=request.temperature,
                top_p=request.top_p,
                top_k=request.top_k,
                repetition_penalty=request.repetition_penalty,
                do_sample=True,
                pad_token_id=tokenizer.eos_token_id
            )
        
        # Decode
        generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
        tokens_generated = outputs.shape[1] - input_length
        
        return GenerateResponse(
            generated_text=generated_text,
            prompt=request.prompt,
            tokens_generated=tokens_generated
        )
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Generation failed: {str(e)}")


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
''')
        
        code = template.render(
            model_id=model_info.get('model_id', 'unknown'),
            use_lora=config.get('use_lora', True),
            quantization=config.get('quantization')
        )
        
        return GeneratedCode(
            code=code,
            filename="api_server.py",
            language="python",
            description="FastAPI server for model inference"
        )
    
    def generate_readme(
        self,
        model_info: Dict[str, Any],
        config: Dict[str, Any],
        training_summary: Dict[str, Any]
    ) -> GeneratedCode:
        """Generate comprehensive README.
        
        Args:
            model_info: Model information
            config: Training configuration
            training_summary: Training results summary
            
        Returns:
            GeneratedCode object
        """
        logger.info("Generating README")
        
        template = Template('''# {{ model_id }} - Fine-Tuned Model

Fine-tuned version of [{{ model_id }}](https://huggingface.co/{{ model_id }}) using the LLM Fine-Tuning Pipeline.

## Model Details

- **Base Model:** {{ model_id }}
- **Parameters:** {{ num_parameters }}
- **Architecture:** {{ architecture }}
- **Task:** {{ task_type }}
- **Fine-tuning Method:** {% if use_lora %}LoRA (Low-Rank Adaptation){% else %}Full Fine-tuning{% endif %}
{% if quantization %}- **Quantization:** {{ quantization }}{% endif %}

## Training Details

### Dataset
- **Samples:** {{ num_samples }}
- **Average Tokens:** {{ avg_tokens }}

### Hyperparameters
```yaml
learning_rate: {{ learning_rate }}
batch_size: {{ batch_size }}
gradient_accumulation_steps: {{ gradient_accumulation_steps }}
epochs: {{ num_epochs }}
optimizer: {{ optimizer }}
scheduler: {{ scheduler }}
{% if use_lora %}
lora_r: {{ lora_r }}
lora_alpha: {{ lora_alpha }}
lora_dropout: {{ lora_dropout }}
{% endif %}
```

### Training Results
- **Final Train Loss:** {{ final_train_loss }}
- **Training Time:** {{ training_time }}
- **GPU Used:** {{ gpu_type }}

## Installation

```bash
pip install torch transformers {% if use_lora %}peft {% endif %}{% if quantization %}bitsandbytes {% endif %}accelerate
```

## Usage

### Basic Inference

```python
from transformers import AutoModelForCausalLM, AutoTokenizer
{% if use_lora %}from peft import PeftModel{% endif %}
import torch

# Load model and tokenizer
tokenizer = AutoTokenizer.from_pretrained("./model")
model = AutoModelForCausalLM.from_pretrained(
    "./model",
    torch_dtype=torch.float16,
    device_map="auto"
)

# Generate text
prompt = "{{ example_prompt }}"
inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
outputs = model.generate(**inputs, max_new_tokens=256)
generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
print(generated_text)
```

### Using the Inference Script

```bash
python inference.py
```

### Using the Gradio App

```bash
python gradio_app.py --model-path ./model --share
```

### Using the API Server

```bash
python api_server.py
```

Then make requests:
```bash
curl -X POST "http://localhost:8000/generate" \\
  -H "Content-Type: application/json" \\
  -d '{"prompt": "Your prompt here", "max_tokens": 256}'
```

## Performance

| Metric | Value |
|--------|-------|
| Parameters | {{ num_parameters }} |
| VRAM (Inference) | {{ vram_inference }} GB |
| VRAM (Training) | {{ vram_training }} GB |
| Inference Speed | {{ inference_speed }} tokens/sec |

## Files

```
.
├── config.json              # Model configuration
├── pytorch_model.bin        # Model weights
├── tokenizer_config.json    # Tokenizer configuration
├── special_tokens_map.json  # Special tokens
├── inference.py             # Inference script
├── gradio_app.py           # Gradio demo
├── api_server.py           # FastAPI server
└── README.md               # This file
```

## License

This model is based on {{ model_id }} and inherits its license.

## Citation

If you use this model, please cite:

```bibtex
@misc{fine-tuned-{{ model_id_safe }},
  author = {Your Name},
  title = {Fine-tuned {{ model_id }}},
  year = {2025},
  publisher = {GitHub/HuggingFace},
  howpublished = {\\url{https://your-url-here}}
}
```

## Acknowledgments

- Base model: [{{ model_id }}](https://huggingface.co/{{ model_id }})
- Fine-tuning pipeline: LLM Fine-Tuning Automation Pipeline
- Framework: Hugging Face Transformers{% if use_lora %}, PEFT{% endif %}

## Contact

For questions or issues, please open an issue on GitHub.
''')
        
        code = template.render(
            model_id=model_info.get('model_id', 'unknown'),
            model_id_safe=model_info.get('model_id', 'unknown').replace('/', '-'),
            num_parameters=model_info.get('parameter_size', 'unknown'),
            architecture=model_info.get('architecture', 'unknown'),
            task_type=config.get('task_type', 'text-generation'),
            use_lora=config.get('use_lora', True),
            quantization=config.get('quantization', 'None'),
            num_samples=training_summary.get('num_samples', 'N/A'),
            avg_tokens=training_summary.get('avg_tokens', 'N/A'),
            learning_rate=config.get('learning_rate', '2e-4'),
            batch_size=config.get('batch_size', 4),
            gradient_accumulation_steps=config.get('gradient_accumulation_steps', 4),
            num_epochs=config.get('num_epochs', 3),
            optimizer=config.get('optimizer', 'adamw'),
            scheduler=config.get('scheduler', 'cosine'),
            lora_r=config.get('lora_config', {}).get('r', 8),
            lora_alpha=config.get('lora_config', {}).get('lora_alpha', 16),
            lora_dropout=config.get('lora_config', {}).get('lora_dropout', 0.05),
            final_train_loss=training_summary.get('final_loss', 'N/A'),
            training_time=training_summary.get('training_time', 'N/A'),
            gpu_type=training_summary.get('gpu_type', 'Unknown'),
            example_prompt=self._get_example_prompt(config.get('task_type', 'text-generation'), 1),
            vram_inference=model_info.get('vram_requirements', {}).get('inference_fp16', 'N/A'),
            vram_training=model_info.get('vram_requirements', {}).get('training_lora_fp16', 'N/A'),
            inference_speed=training_summary.get('inference_speed', 'N/A')
        )
        
        return GeneratedCode(
            code=code,
            filename="README.md",
            language="markdown",
            description="Comprehensive documentation for the fine-tuned model"
        )
    
    def generate_finetuning_script(
        self,
        model_info: Dict[str, Any],
        config: Dict[str, Any]
    ) -> GeneratedCode:
        logger.info(f"Generating standalone fine-tuning script for {model_info.get('model_id')}")

        lora_config = config.get('lora_config') or {}
        target_modules = lora_config.get('target_modules') or ["q_proj", "v_proj"]

        template = Template('''"""
Standalone fine-tuning script for {{ model_id }}
Generated by Parameter Efficient Fine-Tuning Pipeline.

Works standalone: run in Google Colab (GPU runtime recommended) or locally.
All hyperparameters below were configured in the pipeline UI.

Usage:
    1. Colab: Runtime -> Change runtime type -> GPU, then run all cells.
    2. Local: pip install -r requirements, then `python {{ filename }}`

Requirements:
    pip install torch transformers peft bitsandbytes accelerate datasets
"""

# =====================================================================
# 1. CONFIGURATION (generated from your pipeline settings)
# =====================================================================

MODEL_ID = "{{ model_id }}"
DATASET_PATH = "{{ dataset_id }}"  # local JSON/JSONL/CSV path or HuggingFace dataset id
OUTPUT_DIR = "./finetuned-model"

USE_LORA = {{ use_lora }}
USE_QLORA = {{ use_qlora }}
LOAD_IN_4BIT = {{ load_in_4bit }}
LOAD_IN_8BIT = {{ load_in_8bit }}
USE_FP16 = {{ fp16 }}
USE_BF16 = {{ bf16 }}

LEARNING_RATE = {{ learning_rate }}
BATCH_SIZE = {{ batch_size }}
GRADIENT_ACCUMULATION_STEPS = {{ gradient_accumulation_steps }}
NUM_EPOCHS = {{ num_epochs }}
WARMUP_STEPS = {{ warmup_steps }}
WEIGHT_DECAY = {{ weight_decay }}
MAX_GRAD_NORM = {{ max_grad_norm }}
SCHEDULER = "{{ scheduler }}"
OPTIMIZER = "{{ optimizer }}"

MAX_SEQ_LENGTH = {{ max_seq_length }}
VALIDATION_SPLIT = {{ validation_split }}
SEED = {{ seed }}
LOGGING_STEPS = {{ logging_steps }}
SAVE_STEPS = {{ save_steps }}
EVAL_STEPS = {{ eval_steps }}
SAVE_TOTAL_LIMIT = {{ save_total_limit }}
GRADIENT_CHECKPOINTING = {{ gradient_checkpointing }}
GROUP_BY_LENGTH = {{ group_by_length }}

{% if use_lora %}
LORA_R = {{ lora_r }}
LORA_ALPHA = {{ lora_alpha }}
LORA_DROPOUT = {{ lora_dropout }}
LORA_TARGET_MODULES = {{ target_modules }}
LORA_BIAS = "{{ lora_bias }}"
LORA_TASK_TYPE = "{{ lora_task_type }}"
{% endif %}

BNB_4BIT_COMPUTE_DTYPE = "{{ bnb_4bit_compute_dtype }}"
BNB_4BIT_QUANT_TYPE = "{{ bnb_4bit_quant_type }}"
BNB_4BIT_USE_DOUBLE_QUANT = {{ bnb_4bit_use_double_quant }}

# =====================================================================
# 2. IMPORTS & ENVIRONMENT
# =====================================================================

import os
import json

import torch
from datasets import load_dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    Trainer,
    TrainingArguments,
)
{% if use_lora %}from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training{% endif %}

os.environ["TORCH_COMPILE_DISABLE"] = "1"
os.environ["TORCHDYNAMO_DISABLE"] = "1"

GPU_AVAILABLE = torch.cuda.is_available()
print(f"GPU available: {GPU_AVAILABLE}")
if GPU_AVAILABLE:
    print(f"GPU: {torch.cuda.get_device_name(0)}")

# =====================================================================
# 3. SEED & TOKENIZER
# =====================================================================

torch.manual_seed(SEED)
if GPU_AVAILABLE:
    torch.cuda.manual_seed_all(SEED)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# =====================================================================
# 4. MODEL LOADING
# =====================================================================

model_kwargs = {"trust_remote_code": True}

if GPU_AVAILABLE and USE_QLORA and (LOAD_IN_4BIT or LOAD_IN_8BIT):
    compute_dtype = torch.float16 if BNB_4BIT_COMPUTE_DTYPE == "float16" else torch.bfloat16
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=LOAD_IN_4BIT,
        load_in_8bit=LOAD_IN_8BIT,
        bnb_4bit_compute_dtype=compute_dtype,
        bnb_4bit_quant_type=BNB_4BIT_QUANT_TYPE,
        bnb_4bit_use_double_quant=BNB_4BIT_USE_DOUBLE_QUANT,
    )
    model_kwargs.update({
        "quantization_config": bnb_config,
        "device_map": "auto",
        "torch_dtype": torch.float16,
    })
    print(f"Loading {MODEL_ID} with {BNB_4BIT_QUANT_TYPE} quantization...")
else:
    model_kwargs["torch_dtype"] = torch.float32
    print(f"Loading {MODEL_ID} without quantization...")

model = AutoModelForCausalLM.from_pretrained(MODEL_ID, **model_kwargs)

if GRADIENT_CHECKPOINTING:
    model.gradient_checkpointing_enable()

{% if use_lora %}
# =====================================================================
# 5. LoRA ADAPTERS
# =====================================================================

if GPU_AVAILABLE and USE_QLORA and (LOAD_IN_4BIT or LOAD_IN_8BIT):
    model = prepare_model_for_kbit_training(
        model, use_gradient_checkpointing=GRADIENT_CHECKPOINTING
    )

peft_config = LoraConfig(
    r=LORA_R,
    lora_alpha=LORA_ALPHA,
    lora_dropout=LORA_DROPOUT,
    target_modules=LORA_TARGET_MODULES,
    bias=LORA_BIAS,
    task_type=LORA_TASK_TYPE,
    inference_mode=False,
)
model = get_peft_model(model, peft_config)
model.print_trainable_parameters()
{% endif %}

# =====================================================================
# 6. DATASET
# =====================================================================

def load_training_dataset(path: str):
    if os.path.exists(path):
        if path.endswith(".jsonl"):
            return load_dataset("json", data_files=path, split="train")
        if path.endswith(".csv"):
            return load_dataset("csv", data_files=path, split="train")
        return load_dataset("json", data_files=path, split="train")
    return load_dataset(path, split="train")


def ensure_text_column(ds):
    if "text" in ds.column_names:
        return ds

    def generate_text(example):
        if "prompt" in example and "completion" in example:
            return {"text": f"{example['prompt']}\\n\\n{example['completion']}"}
        if "instruction" in example:
            inp = example.get("input", "")
            out = example.get("output", "")
            if inp:
                return {"text": f"### Instruction:\\n{example['instruction']}\\n\\n### Input:\\n{inp}\\n\\n### Response:\\n{out}"}
            return {"text": f"### Instruction:\\n{example['instruction']}\\n\\n### Response:\\n{out}"}
        return {"text": json.dumps(dict(example))}

    return ds.map(generate_text)


dataset = load_training_dataset(DATASET_PATH)
dataset = ensure_text_column(dataset)

if VALIDATION_SPLIT > 0:
    split = dataset.train_test_split(test_size=VALIDATION_SPLIT, seed=SEED)
    train_dataset = split["train"]
    eval_dataset = split["test"]
else:
    train_dataset = dataset
    eval_dataset = None

print(f"Train samples: {len(train_dataset)}" + (f", eval samples: {len(eval_dataset)}" if eval_dataset is not None else ""))

pad_token_id = tokenizer.pad_token_id if tokenizer.pad_token_id is not None else 0


def tokenize_function(examples):
    tokenized = tokenizer(
        examples["text"],
        truncation=True,
        max_length=MAX_SEQ_LENGTH,
        padding="max_length",
    )
    tokenized["labels"] = [
        [t if t != pad_token_id else -100 for t in ids]
        for ids in tokenized["input_ids"]
    ]
    return tokenized


tokenized_train = train_dataset.map(
    tokenize_function, batched=True, remove_columns=train_dataset.column_names
)
tokenized_eval = None
if eval_dataset is not None:
    tokenized_eval = eval_dataset.map(
        tokenize_function, batched=True, remove_columns=eval_dataset.column_names
    )

# =====================================================================
# 7. TRAINING
# =====================================================================

use_paged = GPU_AVAILABLE and "{{ optimizer }}".startswith("paged_")
optim = "{{ optimizer }}" if use_paged else "adamw_torch"

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=NUM_EPOCHS,
    per_device_train_batch_size=BATCH_SIZE,
    gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,
    gradient_checkpointing=GRADIENT_CHECKPOINTING,
    optim=optim,
    learning_rate=LEARNING_RATE,
    weight_decay=WEIGHT_DECAY,
    max_grad_norm=MAX_GRAD_NORM,
    lr_scheduler_type=SCHEDULER,
    warmup_steps=WARMUP_STEPS,
    fp16=(USE_FP16 and not USE_BF16) and GPU_AVAILABLE,
    bf16=USE_BF16 and GPU_AVAILABLE,
    logging_steps=LOGGING_STEPS,
    save_steps=SAVE_STEPS,
    eval_steps=EVAL_STEPS if tokenized_eval is not None else None,
    save_total_limit=SAVE_TOTAL_LIMIT,
    eval_strategy="steps" if tokenized_eval is not None else "no",
    seed=SEED,
    group_by_length=GROUP_BY_LENGTH,
    report_to=[],
    ddp_find_unused_parameters=False,
    remove_unused_columns=False,
    torch_compile=False,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_eval,
    tokenizer=tokenizer,
)

print("Starting training...")
train_result = trainer.train()

# =====================================================================
# 8. SAVE ARTIFACTS
# =====================================================================

trainer.save_model(os.path.join(OUTPUT_DIR, "final_model"))
tokenizer.save_pretrained(os.path.join(OUTPUT_DIR, "final_model"))

with open(os.path.join(OUTPUT_DIR, "training_metrics.json"), "w") as f:
    json.dump(train_result.metrics, f, indent=2)

print(f"Training complete. Model saved to {OUTPUT_DIR}/final_model")
''')

        model_id = model_info.get('model_id') or config.get('model_id', 'unknown')

        code = template.render(
            filename="finetune.py",
            model_id=model_id,
            dataset_id=config.get('dataset_id', 'your-dataset.jsonl'),
            use_lora=config.get('use_lora', True),
            use_qlora=config.get('qlora', True),
            load_in_4bit=config.get('load_in_4bit', True),
            load_in_8bit=config.get('load_in_8bit', False),
            fp16=config.get('fp16', True),
            bf16=config.get('bf16', False),
            learning_rate=config.get('learning_rate', 2e-4),
            batch_size=config.get('batch_size', 4),
            gradient_accumulation_steps=config.get('gradient_accumulation_steps', 1),
            num_epochs=config.get('num_epochs', 3),
            warmup_steps=config.get('warmup_steps', 50),
            weight_decay=config.get('weight_decay', 0.01),
            max_grad_norm=config.get('max_grad_norm', 1.0),
            scheduler=config.get('scheduler', 'cosine'),
            optimizer=config.get('optimizer', 'paged_adamw_8bit'),
            max_seq_length=config.get('max_seq_length', 512),
            validation_split=config.get('validation_split', 0.1),
            seed=config.get('seed', 42),
            logging_steps=config.get('logging_steps', 10),
            save_steps=config.get('save_steps', 100),
            eval_steps=config.get('eval_steps', 100),
            save_total_limit=config.get('save_total_limit', 3),
            gradient_checkpointing=config.get('gradient_checkpointing', True),
            group_by_length=config.get('group_by_length', True),
            lora_r=lora_config.get('r', 8),
            lora_alpha=lora_config.get('lora_alpha', 16),
            lora_dropout=lora_config.get('lora_dropout', 0.05),
            target_modules=target_modules,
            lora_bias=lora_config.get('bias', 'none'),
            lora_task_type=lora_config.get('task_type', 'CAUSAL_LM'),
            bnb_4bit_compute_dtype=config.get('bnb_4bit_compute_dtype', 'float16'),
            bnb_4bit_quant_type=config.get('bnb_4bit_quant_type', 'nf4'),
            bnb_4bit_use_double_quant=config.get('bnb_4bit_use_double_quant', True),
        )

        return GeneratedCode(
            code=code,
            filename="finetune.py",
            language="python",
            description="Complete standalone fine-tuning script with your model and hyperparameters"
        )

    def _get_example_prompt(self, task_type: str, variant: int = 1) -> str:
        """Get example prompt for task type.
        
        Args:
            task_type: Task type
            variant: Prompt variant number
            
        Returns:
            Example prompt
        """
        prompts = {
            "text-generation": [
                "Once upon a time in a land far away,",
                "The future of artificial intelligence is",
                "Explain quantum computing in simple terms:"
            ],
            "text-classification": [
                "This movie was absolutely fantastic!",
                "I'm not sure how I feel about this product.",
                "Worst experience ever. Would not recommend."
            ],
            "summarization": [
                "Summarize the following article: ...",
                "Provide a brief summary of: ...",
                "TL;DR: ..."
            ],
            "question-answering": [
                "Question: What is the capital of France?",
                "Q: How does photosynthesis work?",
                "Answer this question: ..."
            ]
        }
        
        task_prompts = prompts.get(task_type, prompts["text-generation"])
        return task_prompts[variant % len(task_prompts)]
